const PACK_FN=U+'/functions/v1/recommend-packing';
async function renderPacking(){let {data,error}=await sb.from('packing_items').select('*').eq('trip_id',trip.id).order('category').order('created_at');let rows=data||[];$('tabbody').innerHTML=`<div class="panel"><div class="row"><div><h3 style="margin:0">AI 여행 준비물 추천</h3><div class="muted">여행지·계절·기간·일정 특성을 바탕으로 필요한 준비물을 추천합니다.</div></div><button class="btn" id="packAI">AI로 준비물 추천</button></div><div id="packMsg"></div><div id="packSuggest"></div><hr style="border:0;border-top:1px solid #e5eaf1;margin:16px 0"><div class="grid"><div class="field"><label>직접 추가</label><input id="packItem" placeholder="예: 보조배터리"></div><div class="field"><label>분류</label><select id="packCat"><option>필수서류</option><option>의류</option><option>전자기기</option><option>위생/건강</option><option>날씨대비</option><option>활동/관광</option><option>결제/통신</option><option>기타</option></select></div></div><button class="small" id="packAdd">직접 추가</button></div><div style="margin-top:12px">${rows.length?rows.map(x=>`<div class="item"><div class="row"><label style="display:flex;gap:10px;align-items:center"><input type="checkbox" ${x.packed?'checked':''} onchange="togglePacked('${x.id}',this.checked)"><div><b style="${x.packed?'text-decoration:line-through;color:#94a3b8':''}">${e(x.item)}</b><div class="muted">${e(x.category||'기타')}${x.notes?' · '+e(x.notes):''}</div></div></label><button class="small danger" onclick="deletePack('${x.id}')">삭제</button></div></div>`).join(''):'<div class="panel muted">준비물이 아직 없습니다. AI 추천을 눌러보세요.</div>'}</div>`;$('packAI').onclick=recommendPacking;$('packAdd').onclick=addPack;}
async function recommendPacking(){try{let {data:{session}}=await sb.auth.getSession();if(!session)throw Error('로그인이 필요합니다.');M('packMsg','여행지 특성을 분석해 준비물을 추천 중입니다...');let {data:its}=await sb.from('itinerary_items').select('title,place,item_type,notes').eq('trip_id',trip.id);let r=await fetch(PACK_FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':K,'Authorization':'Bearer '+session.access_token},body:JSON.stringify({destination:trip.destination,start_date:trip.start_date,end_date:trip.end_date,days:trip.days,travelers_count:trip.travelers_count,itinerary:its||[],extra_request:trip.extra_request||''})}),j=await r.json();if(!r.ok)throw Error(j.error||'추천 실패');let items=j.items||[];window._packSuggest=items;$('packSuggest').innerHTML=`<div class="panel" style="margin-top:12px;background:#f8fbff"><h3 style="margin-top:0">추천 준비물 ${items.length}개</h3>${items.map((x,i)=>`<label class="item" style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" class="packPick" data-i="${i}" checked><div><b>${e(x.item)}</b> <span class="chip">${e(x.category||'기타')}</span> <span class="chip">${e(x.priority||'권장')}</span><div class="muted">${e(x.reason||'')}</div></div></label>`).join('')}<button class="btn" id="savePackSuggest">선택한 추천 준비물 저장</button></div>`;$('savePackSuggest').onclick=savePackingSuggestions;M('packMsg','추천이 완료되었습니다. 필요한 항목만 선택해 저장하세요.','ok')}catch(x){M('packMsg',x.message,'error')}}
async function savePackingSuggestions(){let u=await need(),items=(window._packSuggest||[]),idx=[...document.querySelectorAll('.packPick:checked')].map(x=>Number(x.dataset.i)),rows=idx.map(i=>items[i]).filter(Boolean).map(x=>({user_id:u.id,trip_id:trip.id,item:x.item,category:x.category||'기타',quantity:1,packed:false,notes:[x.reason,x.tip].filter(Boolean).join(' · ')||null}));if(rows.length){let {error}=await sb.from('packing_items').insert(rows);if(error){M('packMsg',error.message,'error');return}}renderPacking()}
async function addPack(){let u=await need(),item=$('packItem').value.trim();if(!item)return;await sb.from('packing_items').insert({user_id:u.id,trip_id:trip.id,item,category:$('packCat').value,quantity:1,packed:false});renderPacking()}
window.togglePacked=async(id,v)=>{await sb.from('packing_items').update({packed:v}).eq('id',id)};window.deletePack=async id=>{await sb.from('packing_items').delete().eq('id',id);renderPacking()};
async function renderSimple(t){$('tabbody').innerHTML='<div class="panel muted">해당 기능을 준비 중입니다.</div>'}
function showTripAiRequest(){
  if(!trip)return;
  $('scheduleModal').classList.remove('hidden');
  $('scheduleModalTitle').textContent='AI 일정 새로 생성';
  $('scheduleModalBody').innerHTML=`<div class="panel"><div class="muted" style="margin-bottom:12px">현재 여행정보를 기준으로 일정을 다시 만듭니다.<br><b>${e(trip.destination)}</b> · ${e(trip.start_date||'날짜 미정')} ~ ${e(trip.end_date||'')} · ${trip.travelers_count||1}명</div><div class="field"><label>추가 요청사항</label><textarea id="regenReq" placeholder="예: 쇼핑 시간을 넉넉히, 맛집 위주, 아이 동반, 하루 일정은 여유롭게 등">${e(trip.extra_request||'')}</textarea></div><label style="display:flex;gap:8px;align-items:center;margin:10px 0 16px"><input type="checkbox" id="regenNone"> 별도의 요청사항 없음</label><div class="msg" style="background:#fff8e8;color:#7a5a00">새로 생성하면 기존 일정은 새 AI 일정으로 교체됩니다. 예약·경비·준비물 데이터는 유지됩니다.</div><div class="actions" style="margin-top:14px"><button class="btn" id="regenStart">AI 일정 생성</button><button class="small" id="regenCancel">취소</button></div><div id="regenMsg"></div></div>`;
  $('regenCancel').onclick=closeScheduleModal;
  $('regenNone').onchange=()=>{$('regenReq').disabled=$('regenNone').checked;if($('regenNone').checked)$('regenReq').value=''};
  $('regenStart').onclick=regenerateTripAi;
}
async function regenerateTripAi(){
  const b=$('regenStart');
  try{
    let u=await need();
    let {data:{session}}=await sb.auth.getSession();
    if(!session)throw Error('로그인이 필요합니다.');
    if(!trip.destination||!trip.days)throw Error('여행지와 여행기간을 먼저 저장해 주세요.');
    const extra=$('regenNone').checked?'':$('regenReq').value.trim();
    b.disabled=true;b.textContent='AI 일정 생성 중...';M('regenMsg','여행정보와 요청사항을 반영해 새 일정을 만들고 있습니다...');
    let r=await fetch(PLAN,{method:'POST',headers:{'Content-Type':'application/json','apikey':K,'Authorization':'Bearer '+session.access_token},body:JSON.stringify({destination:trip.destination,days:trip.days,nights:trip.nights??Math.max(0,trip.days-1),extraRequest:extra,start_date:trip.start_date,end_date:trip.end_date,travelers_count:trip.travelers_count})});
    let j=await r.json();if(!r.ok)throw Error([j.error,j.detail].filter(Boolean).join(' - ')||'AI 일정 생성 실패');
    let p=j.plan,rows=[];(p.days||[]).forEach(D=>(D.items||[]).forEach((i,k)=>{let f=i.from_previous||{};rows.push({user_id:u.id,trip_id:trip.id,day_no:D.day,start_time:i.time||null,title:i.title||i.place||'일정',place:i.place||null,item_type:i.item_type||'activity',transport:f.mode||i.transport||null,travel_duration_min:f.duration_min??null,travel_distance_km:f.distance_km??null,travel_cost:f.estimated_fare??null,estimated_cost:i.estimated_cost??null,currency:i.currency||f.currency||p.currency||null,meal_type:i.meal_type||null,restaurant_suggestions:i.restaurant_suggestions||[],notes:i.notes||null,sort_order:k})}));
    if(!rows.length)throw Error('AI가 생성한 일정이 비어 있습니다. 다시 시도해 주세요.');
    let {error:de}=await sb.from('itinerary_items').delete().eq('trip_id',trip.id);if(de)throw de;
    let {error:ie}=await sb.from('itinerary_items').insert(rows);if(ie)throw ie;
    let {data:updated,error:ue}=await sb.from('trips').update({extra_request:extra||null,ai_plan:j.text||JSON.stringify(p),ai_grounding:j.grounding||null}).eq('id',trip.id).select().single();if(ue)throw ue;trip=updated;
    closeScheduleModal();tab='itinerary';renderDetail();
  }catch(x){M('regenMsg',x.message,'error')}finally{if(b){b.disabled=false;b.textContent='AI 일정 생성'}}
}
authUI();home();