const bookingCategoryLabels={flight:'항공',lodging:'숙박',attraction:'관광/입장권',transport:'현지교통',restaurant:'식당',event:'공연/체험',other:'기타'};
const bookingStatusLabels={planned:'예약예정',reserved:'예약완료',completed:'이용완료',cancelled:'취소'};
const paymentStatusLabels={unpaid:'미결제',partial:'부분결제',paid:'결제완료',refunded:'환불'};
async function renderBookings(){
 let [br,ir]=await Promise.all([sb.from('bookings').select('*').eq('trip_id',trip.id).order('start_at',{ascending:true}),sb.from('itinerary_items').select('id,day_no,start_time,title').eq('trip_id',trip.id).order('day_no').order('sort_order')]);
 let rows=br.data||[], its=ir.data||[];
 let total=rows.reduce((a,x)=>a+Number(x.amount||0),0),paid=rows.reduce((a,x)=>a+Number(x.paid_amount||0),0);
 $('tabbody').innerHTML=`<div class="kpirow"><div class="kpi"><div class="muted">예약 건수</div><b>${rows.length}</b></div><div class="kpi"><div class="muted">예약 총액</div><b>${money(total)}</b></div><div class="kpi"><div class="muted">결제 완료액</div><b>${money(paid)}</b></div><div class="kpi"><div class="muted">미결제/잔액</div><b>${money(Math.max(0,total-paid))}</b></div></div>
 <div class="panel"><div class="row"><div><h3 style="margin:0">예약 세부정보 추가</h3><div class="muted">항공·숙박·입장권·교통·식당·공연을 한 곳에서 관리합니다.</div></div></div>
 <div class="grid"><div class="field"><label>예약 종류</label><select id="bkCat"><option value="flight">항공</option><option value="lodging">숙박</option><option value="attraction">관광/입장권</option><option value="transport">현지교통</option><option value="restaurant">식당</option><option value="event">공연/체험</option><option value="other">기타</option></select></div>
 <div class="field"><label>예약 항목명</label><input id="bkTitle" placeholder="예: 유니버설 스튜디오 1일권"></div><div class="field"><label>예약처/업체</label><input id="bkProvider" placeholder="예: 공식 홈페이지 / 호텔 / 항공사"></div><div class="field"><label>예약번호</label><input id="bkNo"></div>
 <div class="field"><label>이용 시작</label><input id="bkStart" type="datetime-local"></div><div class="field"><label>이용 종료</label><input id="bkEnd" type="datetime-local"></div><div class="field"><label>장소</label><input id="bkLoc"></div><div class="field"><label>연결 일정</label><select id="bkIt"><option value="">일정 연결 없음</option>${its.map(i=>`<option value="${i.id}">Day ${i.day_no} ${(i.start_time||'').slice(0,5)} ${e(i.title)}</option>`).join('')}</select></div>
 <div class="field"><label>예약 금액</label><input id="bkAmt" type="number" min="0" step="0.01"></div><div class="field"><label>실제 결제금액</label><input id="bkPaid" type="number" min="0" step="0.01"></div><div class="field"><label>통화</label><input id="bkCur" value="KRW"></div><div class="field"><label>예약 상태</label><select id="bkStatus"><option value="planned">예약예정</option><option value="reserved" selected>예약완료</option><option value="completed">이용완료</option><option value="cancelled">취소</option></select></div>
 <div class="field"><label>결제 상태</label><select id="bkPay"><option value="unpaid">미결제</option><option value="partial">부분결제</option><option value="paid" selected>결제완료</option><option value="refunded">환불</option></select></div><div class="field"><label>취소 가능 기한</label><input id="bkCancel" type="datetime-local"></div><div class="field"><label>연락처</label><input id="bkContact"></div><div class="field"><label>예약/확인 URL</label><input id="bkUrl"></div></div>
 <div class="field"><label>예약 메모</label><textarea id="bkNotes" placeholder="체크인 방법, 좌석, 조식, 환불조건 등"></textarea></div><button class="btn" id="bkSave">예약 저장</button><div id="bkMsg"></div></div>
 <div style="margin-top:12px">${rows.length?rows.map(x=>{let it=its.find(i=>i.id===x.itinerary_item_id);return `<div class="item"><div class="row"><div><div class="chips"><span class="chip">${e(bookingCategoryLabels[x.category]||x.category||'기타')}</span><span class="chip">${e(bookingStatusLabels[x.status]||x.status||'')}</span><span class="chip">${e(paymentStatusLabels[x.payment_status]||x.payment_status||'')}</span></div><h3 style="margin:8px 0 4px">${e(x.title||x.provider||'예약')}</h3><div class="muted">${e(x.provider||'')}${x.reservation_no?' · 예약번호 '+e(x.reservation_no):''}${x.start_at?' · '+e(new Date(x.start_at).toLocaleString('ko-KR')):''}</div>${x.location?`<div class="muted">📍 ${e(x.location)}</div>`:''}${it?`<div class="muted">연결 일정: Day ${it.day_no} ${e(it.title)}</div>`:''}<div class="route">예약 ${money(x.amount||0)} ${e(x.currency||'')} · 결제 ${money(x.paid_amount??0)} ${e(x.currency||'')}</div>${x.notes?`<div class="memobox">${e(x.notes)}</div>`:''}</div><button class="small danger" onclick="deleteBooking('${x.id}')">삭제</button></div></div>`}).join(''):'<div class="panel muted">등록된 예약이 없습니다.</div>'}</div>`;
 $('bkSave').onclick=saveBooking;
}
async function saveBooking(){try{let u=await need(),title=$('bkTitle').value.trim();if(!title)throw Error('예약 항목명을 입력하세요.');let p={user_id:u.id,trip_id:trip.id,category:$('bkCat').value,title,provider:$('bkProvider').value.trim()||null,reservation_no:$('bkNo').value.trim()||null,start_at:$('bkStart').value?new Date($('bkStart').value).toISOString():null,end_at:$('bkEnd').value?new Date($('bkEnd').value).toISOString():null,location:$('bkLoc').value.trim()||null,itinerary_item_id:$('bkIt').value||null,amount:$('bkAmt').value===''?null:Number($('bkAmt').value),paid_amount:$('bkPaid').value===''?0:Number($('bkPaid').value),currency:$('bkCur').value.trim()||'KRW',status:$('bkStatus').value,payment_status:$('bkPay').value,cancel_by:$('bkCancel').value?new Date($('bkCancel').value).toISOString():null,contact:$('bkContact').value.trim()||null,booking_url:$('bkUrl').value.trim()||null,notes:$('bkNotes').value.trim()||null,booked_at:new Date().toISOString()};let {error}=await sb.from('bookings').insert(p);if(error)throw error;renderBookings()}catch(x){M('bkMsg',x.message,'error')}}
window.deleteBooking=async id=>{if(confirm('예약 기록을 삭제할까요?')){await sb.from('bookings').delete().eq('id',id);renderBookings()}};