// v54: one-card AI alternatives; only the applied option changes maps and exports.
(()=>{const states=new Map();
const norm=(x,cur)=>{const m=x.from_previous||{};return{day_no:cur.day_no,start_time:cur.start_time,title:x.title||x.place||'대체 일정',place:x.place||x.title||null,item_type:x.item_type||cur.item_type||'activity',transport:m.mode||x.transport||cur.transport||null,travel_duration_min:m.duration_min??x.travel_duration_min??null,travel_distance_km:m.distance_km??x.travel_distance_km??null,travel_cost:m.estimated_fare??x.travel_cost??null,estimated_cost:x.estimated_cost??null,currency:x.currency||m.currency||cur.currency||null,meal_type:x.meal_type||null,restaurant_suggestions:x.restaurant_suggestions||[],shopping_suggestions:x.shopping_suggestions||[],notes:x.notes||null,latitude:null,longitude:null,geocoded_at:null}};
const key=x=>[x.title,x.place].map(v=>String(v||'').trim().toLowerCase()).join('|');
function card(x,i,on){let move=x.travel_duration_min!=null?`${e(x.transport||'이동')} · 약 ${e(x.travel_duration_min)}분${x.travel_distance_km!=null?` · ${e(x.travel_distance_km)}km`:''}`:'이동정보는 적용 후 자동 확인';return `<label class="alternative-option ${on?'selected':''}"><input type="checkbox" class="alternative-pick" data-index="${i}" ${on?'checked':''}><span class="alternative-number">${i+1}안</span><span class="alternative-copy"><b>${e(x.title)}</b><span>${e(x.place||'')}</span><small>${move}${x.estimated_cost!=null?` · 예상 ${e(x.estimated_cost)} ${e(x.currency||'')}`:''}</small>${x.notes?`<small>${e(x.notes)}</small>`:''}</span></label>`}
function draw(id){let s=states.get(id),h=$('alternativeResults');if(!s||!h)return;h.innerHTML=`<div class="alternative-list">${s.options.map((x,i)=>card(x,i,i===s.selected)).join('')}</div><div class="msg" style="background:#eef6ff;color:#234">체크한 일정 하나만 실제 일정과 지도에 반영됩니다. 적용 전까지 현재 일정은 바뀌지 않습니다.</div><div class="actions"><button class="btn" id="alternativeApply">선택 일정 적용</button><button class="small" id="alternativeRetry">다시 제안받기</button></div>`;h.querySelectorAll('.alternative-pick').forEach(b=>b.onchange=()=>{s.selected=+b.dataset.index;draw(id)});$('alternativeApply').onclick=()=>apply(id);$('alternativeRetry').onclick=()=>generate(id)}
window.openAlternativeSuggestions=id=>{let cur=(window._i||[]).find(x=>x.id===id);if(!cur)return;states.set(id,{options:[cur],selected:0});$('scheduleModalTitle').textContent='AI 대체 일정 제안';$('scheduleModalBody').innerHTML=`<div class="panel alternative-panel"><div class="alternative-current"><span>현재 일정 · 1안</span><b>Day ${e(cur.day_no)} ${(cur.start_time||'').slice(0,5)} · ${e(cur.title)}</b><small>${e(cur.place||'')}</small></div><div class="field"><label>대체 일정 요청사항(선택)</label><textarea id="alternativeRequest" placeholder="예: 실내 관광지 위주, 쇼핑 대신 전통문화 체험, 이동시간 30분 이내"></textarea></div><div class="actions"><button class="btn" id="alternativeGenerate">2안·3안·4안 제안받기</button><button class="small" id="alternativeCancel">취소</button></div><div id="alternativeMessage"></div><div id="alternativeResults"></div></div>`;$('scheduleModal').classList.remove('hidden');$('alternativeGenerate').onclick=()=>generate(id);$('alternativeCancel').onclick=closeScheduleModal};
async function generate(id){let s=states.get(id),cur=s?.options[0],b=$('alternativeGenerate')||$('alternativeRetry');if(!cur)return;try{let{data:{session}}=await sb.auth.getSession();if(!session)throw Error('로그인이 필요합니다.');b.disabled=true;b.textContent='AI가 대체 일정 찾는 중...';M('alternativeMessage','현재 일정과 앞뒤 동선을 유지하면서 대체 후보를 찾고 있습니다...');let rows=window._i||[],p=rows.findIndex(x=>x.id===id),prev=p>0&&rows[p-1].day_no===cur.day_no?rows[p-1]:null,next=p>=0&&rows[p+1]?.day_no===cur.day_no?rows[p+1]:null,req=$('alternativeRequest')?.value.trim()||'';let ins=`Day ${cur.day_no} ${String(cur.start_time||'').slice(0,5)}의 현재 일정 "${cur.title}"(${cur.place||''})만 대체할 후보를 제안하세요. 전체 일정은 재구성하지 마세요. 앞 일정은 ${prev?.title||'없음'}, 다음 일정은 ${next?.title||'없음'}입니다. 같은 시간대에 가능한 서로 다른 대체 장소 3개를 만들고 각 후보에 장소, 이동수단, 이동시간, 거리, 비용, 주변 맛집과 쇼핑 정보를 포함하세요. 현재 장소는 제외하세요.${req?` 사용자 요청: ${req}`:''}`;let r=await fetch(PLAN,{method:'POST',headers:{'Content-Type':'application/json',apikey:K,Authorization:'Bearer '+session.access_token},body:JSON.stringify({destination:trip.destination,days:1,nights:0,start_date:trip.start_date,end_date:trip.end_date,travelers_count:trip.travelers_count,extraRequest:ins,lodging:{name:trip.lodging_name,address:trip.lodging_address}})}),j=await r.json();if(!r.ok)throw Error([j.error,j.detail].filter(Boolean).join(' - ')||'대체 일정 제안 실패');let seen=new Set([key(cur)]),alts=(j.plan?.days||[]).flatMap(d=>d.items||[]).map(x=>norm(x,cur)).filter(x=>{let k=key(x);if(!x.title||seen.has(k))return false;seen.add(k);return true}).slice(0,3);if(alts.length<2)throw Error('서로 다른 후보가 충분하지 않습니다. 요청사항을 바꿔 다시 시도해 주세요.');s.options=[cur,...alts];s.selected=0;M('alternativeMessage',`${alts.length}개의 대체 일정을 찾았습니다. 원하는 안을 체크하세요.`,'ok');draw(id)}catch(x){M('alternativeMessage',x.message,'error')}finally{if(b){b.disabled=false;b.textContent=b.id==='alternativeRetry'?'다시 제안받기':'2안·3안·4안 제안받기'}}}
const historyKey=id=>`tripmate:itinerary-history:${trip?.id||''}:${id}`;
function getHistory(id){try{return JSON.parse(localStorage.getItem(historyKey(id))||'[]')}catch{return[]}}
function saveHistory(id,item){const fields=['day_no','start_time','title','place','item_type','transport','travel_duration_min','travel_distance_km','travel_cost','estimated_cost','currency','meal_type','restaurant_suggestions','shopping_suggestions','notes','latitude','longitude','geocoded_at'];let snapshot={};fields.forEach(k=>snapshot[k]=item[k]??null);let h=getHistory(id);h.push(snapshot);localStorage.setItem(historyKey(id),JSON.stringify(h.slice(-10)))}
async function apply(id){let s=states.get(id),pick=s?.options[s.selected],b=$('alternativeApply');if(!pick)return;if(s.selected===0){closeScheduleModal();return}try{b.disabled=true;b.textContent='일정과 지도에 반영 중...';let old=(window._i||[]).find(x=>x.id===id),payload={...pick};['id','user_id','trip_id','created_at','sort_order'].forEach(k=>delete payload[k]);saveHistory(id,old);let{error}=await sb.from('itinerary_items').update(payload).eq('id',id);if(error)throw error;if(typeof cascadeAfterEdit==='function')await cascadeAfterEdit(old,{...old,...payload});states.delete(id);closeScheduleModal();await renderIt()}catch(x){M('alternativeMessage','선택 일정을 반영하지 못했습니다: '+x.message,'error');b.disabled=false;b.textContent='선택 일정 적용'}}
window.undoAlternative=async id=>{let h=getHistory(id);if(!h.length)return;let previous=h[h.length-1],current=(window._i||[]).find(x=>x.id===id);if(!confirm(`“${current?.title||'현재 일정'}”을 이전 일정 “${previous.title||''}”으로 되돌릴까요?`))return;let{error}=await sb.from('itinerary_items').update(previous).eq('id',id);if(error){alert('이전 일정을 복구하지 못했습니다: '+error.message);return}h.pop();localStorage.setItem(historyKey(id),JSON.stringify(h));await renderIt()};
const baseRenderIt=window.renderIt;
window.renderIt=async function(){await baseRenderIt();document.querySelectorAll('#tabbody .item').forEach((node,i)=>{let item=(window._i||[])[i],actions=node.querySelector('.row .actions');if(!item||!actions||actions.querySelector('.alternative-trigger'))return;let button=document.createElement('button');button.className='small alternative-trigger';button.textContent='대체 일정 제안';button.onclick=()=>openAlternativeSuggestions(item.id);let memo=[...actions.querySelectorAll('button')].find(x=>x.textContent.trim()==='메모');actions.insertBefore(button,memo||actions.firstChild);if(getHistory(item.id).length){let undo=document.createElement('button');undo.className='small alternative-undo';undo.textContent='이전 일정으로 되돌리기';undo.onclick=()=>undoAlternative(item.id);actions.insertBefore(undo,memo||actions.firstChild)}})};
})();
